<a href="https://colab.research.google.com/github/lalatendu7/Breast-cancer-detection-in-ML/blob/main/KNN_details_28_01_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IMPLEMENTATION OF KNN


In [ ]:

import numpy as np
import math
#Create a numpy matrix...data set...
A = np.array([[1, 4, 5, 4],
              [5, 8, 9, 14],
              [6, 7, 11, 13],
              [1,4,5,3],
              [5, 8, 9, 14],
              [4, 7, 8, 13],
              [1,4,6,4],
              [5,5,4,5],
              [5, 8, 9, 14],
              [6, 7, 11, 12]])
class_level=[1,2,2,1,2,2,1,1,2,2] #Associated class level
row,col=A.shape

In [ ]:
#Compute the equlidian distance...
def distance(x,y):
    sum=0.0
    for i in range(len(x)):
        sum= sum + (x[i] -y[i])* (x[i] - y[i])

    return math.sqrt(sum)

In [ ]:
#Define function for classification...

def knn_classification(A,new_sample,k):
    row,col=A.shape
    #Get the distance from all sample of the data set and store in d...
    d=[]
    for i in range(row):
        dis = distance( new_sample , A[i])
        d.append(dis)
    print("The distance from all the points are:\n",d)
    index=np.argsort(d)#sort the distance based on the value index...
    print("sorted index: \n",index)

    ctr1=0
    ctr2=0
    for i in range(k):
        if ( class_level[index[i]]==1 ):
            ctr1=ctr1+1
        else:
            ctr2=ctr2+1
    if(ctr1>ctr2):
        return 1
    else:
        return 2


In [ ]:
#Prediction....
#Generate test sample....
sample_1 = [1,4,5,4] #new sample....
k=3
c=knn_classification(A,sample_1,k);
print("The class in which the new sample belong is: ",c)

print("\nNext sample class level is\n")
sample_2 = [6, 7, 11, 12]
c=knn_classification(A,sample_2,k);
print("The class in which the new sample belong is: ",c)

The distance from all the points are:
 [0.0, 12.165525060596439, 12.288205727444508, 1.0, 12.165525060596439, 10.392304845413264, 1.0, 4.358898943540674, 12.165525060596439, 11.575836902790225]
sorted index: 
 [0 3 6 7 5 9 1 4 8 2]
The class in which the new sample belong is:  1

Next sample class level is

The distance from all the points are:
 [11.575836902790225, 3.1622776601683795, 1.0, 12.288205727444508, 3.1622776601683795, 3.7416573867739413, 11.090536506409418, 10.14889156509222, 3.1622776601683795, 0.0]
sorted index: 
 [9 2 1 4 8 5 7 6 0 3]
The class in which the new sample belong is:  2


# Generate synthetic data for two classes

In [ ]:
#apply KNN on synthetic data...
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification

# Generate synthetic data for two classes
X, y = make_classification(
    n_samples=60,        # Number of samples
    n_features=6,        # Number of features
    n_classes=2,         # Number of classes
    random_state=42      # Seed for reproducibility
)

In [ ]:
#divide the data set into two sets, trai set and test set...
X_train=X[0:50]
X_test=X[50:61]
print(X_test)

y_train=y[0:50]
y_test=y[50:61]
print(y_test)

[[ 0.43105621 -0.07659294 -0.85715756  0.62566735  0.41148157 -0.80499816]
 [ 0.91587776  0.06243672  0.48247242 -1.0708925   1.67595303 -1.9892455 ]
 [-1.50638729  0.52443832 -1.1429703   0.05820872 -0.52382241  2.4952102 ]
 [-0.55859466 -0.0624513   0.65139125  0.95400176 -1.10893061  1.24342208]
 [-0.810488    0.21632966 -0.48423407 -1.51936997 -0.51622264  1.42403555]
 [-0.19771377  0.15559822 -0.81581028 -0.88951443  0.24014872  0.22005263]
 [ 0.56760369 -0.51904185  0.51378595  0.51503527 -0.94698832 -0.54214784]
 [-1.03128187  1.0719947   0.21645859 -0.73036663  2.17965475  0.82535439]
 [-0.64827236 -0.08850068 -0.93782504 -1.37766937 -1.34400607  1.46288529]
 [-0.85319352  0.54072612 -0.65160035  0.04557184  0.57090427  1.11147473]]
[1 1 0 0 1 1 0 1 0 1]


In [ ]:
#Define function for classification...

def knn_classification(A,new_sample,k,y_train):
    row,col=A.shape
    #Get the distance from all sample of the data set and store in d...
    d=[]
    for i in range(row):
        dis = distance( new_sample , A[i])
        d.append(dis)
    #print("The distance from all the points are:\n",d)
    index=np.argsort(d)#sort the distance based on the value index...
    #print("sorted index: \n",index)

    ctr1=0
    ctr2=0
    for i in range(k):
        if ( y_train[index[i]]==1 ):
            ctr1=ctr1+1
        else:
            ctr2=ctr2+1
    if(ctr1>ctr2):
        return 1
    else:
        return 0

In [ ]:
#Function print accuracy

def print_accuracy(y_pred,y_test):
    ctr=0
    for i in range(len(y_pred)):
        if y_pred[i] == y_test[i]:
            ctr=ctr+1

    accuracy=ctr/len(y_test)*100
    return accuracy


In [ ]:
y_pred=[]
k=7
for i in range(len(X_test)):
    cls_label=knn_classification(X_train,X_test[i],k,y_train)
    y_pred.append(cls_label)
print(y_pred)

print

[1, 1, 0, 1, 1, 1, 0, 1, 0, 1]


<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [ ]:
v=print_accuracy(y_pred,y_test)
print(v)

90.0
